* Tasks
** Convert string iterators to char iterators
   I wrote a custom string iterator, as a bit of a hack... ideally, it should just iterate the string as a char, and cast to a string if it _really_ needs to!
** len() function
   ... we totally forgot it :P
   
   It's now working for strings, but for lists it's janky...
   The issue is with anonymous lists right now.
   In the future, we should create headers for all anonymous lists!
** List operations
   https://docs.python.org/2/tutorial/datastructures.html
** [#C] Variable length arguments
   I'll put this on the back burner for now.. but to implement things like print() properly, we should support variable length arguments.
* Bugs
** Division is broken
   e.g.
   #+begin_src python
     print(3 / 4)
   #+end_src
   
   Will print a float value, but C++ will do an integer division.
   For now, we could force users to use the "//" operator...
   But in the future, we should support floats of course
** Line number reporting is broken
   When the javelinParser ouputs errors on line numbers, it's technically the scoped line numbers, not the source line numbers.
** Declaring a function, then a var with the same name gives a garbage error message
   #+begin_src python
     def hi() -> int:
         boop = 3
     hi = 4
   #+end_src
   Assigning a variable twice creates duplicate two definitions
** Variable redeclarations are broken (inside new scopes)
